# Generated by Django 3.1.2 on 2021-01-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=60)),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To', models.CharField(max_length=20)),
                ('From', models.CharField(max_length=20)),
                ('Amount', models.CharField(max_length=5)),
                ('Result', models.CharField(max_length=10)),
                ('Conversion_factor', models.CharField(max_length=10)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
