# Generated by Django 3.1.2 on 2021-01-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_currency', '0002_feedback_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='shortform',
            field=models.CharField(default='', editable=False, max_length=6),
        ),
    ]
