# Generated by Django 3.1.2 on 2021-01-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_currency', '0003_currency_shortform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='shortform',
            field=models.CharField(default='', max_length=6),
        ),
    ]
