# Generated by Django 3.1.2 on 2021-01-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_currency', '0004_auto_20210109_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='Conversion_factor',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='history',
            name='Result',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
