# Generated by Django 3.1.2 on 2021-01-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_currency', '0005_auto_20210109_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='Amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='Conversion_factor',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='Result',
            field=models.FloatField(blank=True),
        ),
    ]
