# Generated by Django 3.1.2 on 2021-01-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_currency', '0006_auto_20210109_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='Amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='From',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='To',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
