# Generated by Django 3.1.2 on 2021-01-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_currency', '0008_auto_20210109_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='Conversion_factor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
