# Generated by Django 3.1.2 on 2021-01-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_currency', '0009_auto_20210109_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='Amount',
            field=models.FloatField(blank=True, default=1.0),
        ),
        migrations.AlterField(
            model_name='history',
            name='From',
            field=models.CharField(default='USD', max_length=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='To',
            field=models.CharField(default='INR', max_length=20),
        ),
    ]
