# Generated by Django 3.1.2 on 2021-01-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_currency', '0010_auto_20210109_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='From',
            field=models.CharField(blank=True, default='USD', max_length=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='To',
            field=models.CharField(blank=True, default='INR', max_length=20),
        ),
    ]
